[tools]
"aqua:astral-sh/uv"              = "0.9.21"
"aqua:cli/cli"                   = "2.83.2"
"aqua:golangci/golangci-lint"    = "2.7.2"
"aqua:koalaman/shellcheck"       = "0.11.0"
"aqua:mvdan/sh"                  = "3.12.0"
bun                              = "1.3.5"
node                             = "22.19.0"
"npm:@anthropic-ai/claude-code"  = "2.0.14"
"npm:@google/gemini-cli"         = "0.23.0"
"npm:@taplo/cli"                 = "0.7.0"
"npm:@typescript/native-preview" = "7.0.0-dev.20251014.1"
"npm:ccusage"                    = "18.0.5"
"npm:prettier"                   = "3.7.4"
