[tools]
"aqua:astral-sh/uv"              = "0.9.26"
"aqua:cli/cli"                   = "2.86.0"
"aqua:golangci/golangci-lint"    = "2.9.0"
"aqua:koalaman/shellcheck"       = "0.11.0"
"aqua:mvdan/sh"                  = "3.12.0"
bun                              = "1.3.5"
go                               = "1.25.6"
node                             = "22.19.0"
"npm:@anthropic-ai/claude-code"  = "2.0.14"
"npm:@google/gemini-cli"         = "0.27.0"
"npm:@taplo/cli"                 = "0.7.0"
"npm:@typescript/native-preview" = "7.0.0-dev.20251014.1"
"npm:ccusage"                    = "18.0.5"
"npm:opencode-ai"                = "1.1.48"
"npm:prettier"                   = "3.8.1"
python                           = "3.14.0"

[settings.npm]
bun = true

[settings.pipx]
uvx = true
