[[snippets]]
name            = "atuin search -i"
snippet         = "atuin search -i"
trigger-pattern = "(ats|ase)"

[[snippets]]
name    = "atuin stats"
snippet = "atuin stats"
trigger = "atst"

[[snippets]]
name            = "aqua search"
snippet         = "aqua g"
trigger-pattern = "(^as$|^ag$)"

[[snippets]]
name            = "code ."
snippet         = "code ."
trigger-pattern = "^c\\.$"

[[snippets]]
name            = "caffeinate"
snippet         = "caffeinate"
trigger-pattern = "^ca$"

[[snippets]]
name            = "cal -3"
snippet         = "cal -3"
trigger-pattern = "^c3$"

[[snippets]]
name            = "cal -y"
snippet         = "cal -y"
trigger-pattern = "^cy$"

[[snippets]]
name    = "ccmanager"
snippet = "ccmanager"
trigger = "ccm"

[[snippets]]
cursor          = "ðŸ‘‡"
evaluate        = true
name            = "ccmanager devcontainer(claude)"
snippet         = "ccmanager --devc-up-command \"devc-up-wrapper devcontainer up --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json\" --devc-exec-command \"devcontainer exec --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json claude --dangerously-skip-permissions\""
trigger-pattern = "(^ccmc$|ccmcc)"

[[snippets]]
name    = "ccmanager devcontainer(gemini)"
snippet = "ccmanager --devc-up-command \"devc-up-wrapper devcontainer up --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json\" --devc-exec-command \"devcontainer exec --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json gemini --yolo\""
trigger = "ccmcg"

[[snippets]]
name    = "ccmanager devcontainer(opencode)"
snippet = "ccmanager --devc-up-command \"devc-up-wrapper devcontainer up --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json\" --devc-exec-command \"devcontainer exec --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json opencode\""
trigger = "ccmco"

[[snippets]]
name    = "ccmanager devcontainer(copilot)"
snippet = "ccmanager --devc-up-command \"devc-up-wrapper devcontainer up --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json\" --devc-exec-command \"devcontainer exec --workspace-folder . --config $HOME/.config/devcontainer/devcontainer.json copilot --yolo\""
trigger = "ccmcp"

[[snippets]]
name            = "echo"
snippet         = "echo"
trigger-pattern = "^e$"

[[snippets]]
name            = "exec $SHELL -l"
snippet         = "exec $SHELL -l"
trigger-pattern = "^es$"

[[snippets]]
name            = "ls -la"
snippet         = "ls -la"
trigger-pattern = "^la$"

[[snippets]]
name            = "ls -l"
snippet         = "ls -l"
trigger-pattern = "^ll$"

[[snippets]]
name            = "multi-worktree"
snippet         = "multi-worktree"
trigger-pattern = "^mw$"

[[snippets]]
name            = "nvim"
snippet         = "nvim"
trigger-pattern = "(^nv$|^v$)"

[[snippets]]
name            = "nvim ."
snippet         = "nvim ."
trigger-pattern = "(^n\\.|^v\\.)"

[[snippets]]
name            = "sudo"
snippet         = "sudo"
trigger-pattern = "^s$"

[[snippets]]
name            = "which"
snippet         = "which"
trigger-pattern = "^w$"

[[snippets]]
name            = "yazi"
snippet         = "yazi"
trigger-pattern = "^y$"

[[snippets]]
name            = "czg"
snippet         = "czg"
trigger-pattern = "^cz$"

[[snippets]]
name    = "czg ai"
snippet = "czg ai"
trigger = "cza"

[[snippets]]
name    = "czg ai(English)"
snippet = "CZ_LANG=en czg ai"
trigger = "czae"

[[snippets]]
name            = "gotip --view=history"
snippet         = "gotip --view=history -- --tags=shipper_resolver_test,admin_resolver_test,forwarder_resolver_test,resolver_test"
trigger-pattern = "^got$"

[[snippets]]
context         = "^go\\s"
global          = true
name            = "./..."
snippet         = "./..."
trigger-pattern = "(\\.\\.\\.\\.|\\.4)"

[[snippets]]
name            = "ghost"
snippet         = "ghost"
trigger-pattern = "^gt$"

[[snippets]]
name            = "ghost run"
snippet         = "ghost run"
trigger-pattern = "^gtr$"

[[snippets]]
name    = "jira copy title"
snippet = "jira issue list -a$(jira me) -s~Done --plain | column -ts $'\\t' | fzf | awk '{s=$3; for(i=4;i<=NF-1;i++) s=s \" \"$i; print \"[\"$2\"]\"s}' | sed 's/ /\\\\ /g; s/\\[/\\\\\\[/g' | cb"
trigger = "jct"

[[snippets]]
name            = "jira issue list -a$(jira me) -s~Done"
snippet         = "jira issue list -a$(jira me) -s~Done"
trigger-pattern = "^jl$"

[[snippets]]
name            = "jira issue list -a$(jira me) all"
snippet         = "jira issue list -a$(jira me)"
trigger-pattern = "^jla$"

[[snippets]]
name    = "jira issue list -s~Done"
snippet = "jira issue list -s~Done"
trigger = "jll"

[[snippets]]
name    = "jira issue list all"
snippet = "jira issue list"
trigger = "jlla"

[[snippets]]
name            = "koji --config ~/.config/koji/config.toml"
snippet         = "koji --config ~/.config/koji/config.toml"
trigger-pattern = "^ko$"

[[snippets]]
name            = "rtty"
snippet         = "rtty run zsh --font-size 12"
trigger-pattern = "(^rt$|^bt$)"

[[snippets]]
global          = true
name            = "ug -QPn"
snippet         = "ug -QPn"
trigger-pattern = "(^ug$|igrep)"

[[snippets]]
name            = "up --noinput"
snippet         = "up --noinput"
trigger-pattern = "^up$"

[[snippets]]
name            = "zinit"
snippet         = "zinit"
trigger-pattern = "^zi$"

[[snippets]]
name            = "ji"
snippet         = "ji"
trigger-pattern = "^zz$"

[[snippets]]
global          = true
name            = "|"
snippet         = "|"
trigger-pattern = "^pi$"

[[snippets]]
global  = true
name    = "|& spacer --after 5"
snippet = "|& spacer --after 5"
trigger = "sp"

[[snippets]]
context = ".*claude\\s"
global  = true
name    = "(claude) --dangerously-skip-permissions"
snippet = "--dangerously-skip-permissions"
trigger = "yl"

[[snippets]]
context = ".*(copilot|gemini)\\s"
global  = true
name    = "(copilot|gemini) --yolo"
snippet = "--yolo"
trigger = "yl"

[[snippets]]
context = ".*delta\\s"
global  = true
name    = "(delta) --no-gitconfig"
snippet = "--no-gitconfig"
trigger = "ng"
