[[snippets]]
name = "ni ci"
trigger-pattern = "^nc$"
snippet = "ni ci"
if = "[[ -f \"./pnpm-lock.yaml\" ]] || [[ -f \"./package-lock.json\" ]] || [[ -f \"./yarn.lock\" ]] || [[ -f \"./bun.lock\" ]] || [[ -f \"./deno.lock\" ]]"

[[snippets]]
name = "ni add"
trigger-pattern = "^na$"
snippet = "ni add"
if = "[[ -f \"./pnpm-lock.yaml\" ]] || [[ -f \"./package-lock.json\" ]] || [[ -f \"./yarn.lock\" ]] || [[ -f \"./bun.lock\" ]] || [[ -f \"./deno.lock\" ]]"

[[snippets]]
name = "ni run"
trigger-pattern = "^nr$"
snippet = "ni run"
if = "[[ -f \"./pnpm-lock.yaml\" ]] || [[ -f \"./package-lock.json\" ]] || [[ -f \"./yarn.lock\" ]] || [[ -f \"./bun.lock\" ]] || [[ -f \"./deno.lock\" ]]"

[[snippets]]
name = "ni run build"
trigger = "nrb"
snippet = "ni run build"
if = "[[ -f \"./pnpm-lock.yaml\" ]] || [[ -f \"./package-lock.json\" ]] || [[ -f \"./yarn.lock\" ]] || [[ -f \"./bun.lock\" ]] || [[ -f \"./deno.lock\" ]]"

[[snippets]]
name = "ni run dev"
trigger = "nrd"
snippet = "ni run dev"
if = "[[ -f \"./pnpm-lock.yaml\" ]] || [[ -f \"./package-lock.json\" ]] || [[ -f \"./yarn.lock\" ]] || [[ -f \"./bun.lock\" ]] || [[ -f \"./deno.lock\" ]]"

[[snippets]]
name = "ni run fix"
trigger = "nrf"
snippet = "ni run fix"
if = "[[ -f \"./pnpm-lock.yaml\" ]] || [[ -f \"./package-lock.json\" ]] || [[ -f \"./yarn.lock\" ]] || [[ -f \"./bun.lock\" ]] || [[ -f \"./deno.lock\" ]]"

[[snippets]]
name = "ni run lint"
trigger = "nrl"
snippet = "ni run lint"
if = "[[ -f \"./pnpm-lock.yaml\" ]] || [[ -f \"./package-lock.json\" ]] || [[ -f \"./yarn.lock\" ]] || [[ -f \"./bun.lock\" ]] || [[ -f \"./deno.lock\" ]]"

[[snippets]]
name = "ni run test"
trigger-pattern = "(^nrt$|^nt$)"
snippet = "ni run test"
if = "[[ -f \"./pnpm-lock.yaml\" ]] || [[ -f \"./package-lock.json\" ]] || [[ -f \"./yarn.lock\" ]] || [[ -f \"./bun.lock\" ]] || [[ -f \"./deno.lock\" ]]"

[[snippets]]
name = "ni run test"
trigger = "nrtd"
snippet = "ni run test $(git diff --name-only --line-prefix=$(git rev-parse --show-toplevel)/ origin/master...HEAD | grep -E '.*spec.*')"
if = "[[ -f \"./pnpm-lock.yaml\" ]] || [[ -f \"./package-lock.json\" ]] || [[ -f \"./yarn.lock\" ]] || [[ -f \"./bun.lock\" ]] || [[ -f \"./deno.lock\" ]]"
