# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"
[mgr]
prepend_keymap = [
    { on = "z", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },
    { on = "Z", run = "plugin bunny fuzzy", desc = "Start bunny.yazi fuzzy search" },
]
